### ISSUE TITLE
No noticeable improvement, something I'm missing?

### ISSUE THREAD

**Issue by andyjeffries** [evilmartians/capybara-thruster#2]
## What did you do?

Installed the gem in my `Gemfile`, added `Capybara.server = :thruster` to my `rails_helper.rb`

## What did you expect to happen?

Some improvement in performance.

## What actually happened?

I have a long intensive smoke test that fully exercises onboarding customers, and our main product feature. It ran without this gem in 8m17s and with this gem in 8m19s (on my M1 Max MacBook Pro w/64GB RAM), so within the bounds of "the same" for an experiment.

Maybe there's some additional step to enable it?

## Environment

**Ruby Version:** 3.3.0

**Framework Version (Rails, whatever):** Rails 7.1.3.2

**Capybara Thruster Version:** 0.1.0

**Comment by palkan** [comment]
The performance improvement is not guaranteed for any use case. We highlight in the Readme that serving static files is what we can potentially optimize by serving them via Thruster (and that's we observed in the applications we migrated to Thruster, all HTML-first). 

Depending on the number of assets to serve, whether navigation is done via full page reload or smth like Turbo Drive, and you previous configuration (e.g., if you already used multithreaded Puma, which is also better than the default configuration), the effect may vary.
