### ISSUE TITLE
Doesn't seem to work with Rack >= 3 out of the box

### ISSUE THREAD

**Issue by julianrubisch** [evilmartians/capybara-thruster#4]
## What did you do?
I just added capybara-thruster to my `application_system_test_case.rb`:

```rb
Capybara.server = :thruster, {puma_options: {Silent: true}}
```

## What did you expect to happen?
That it works.

## What actually happened?

Got
```
LoadError: cannot load such file -- rack/handler (LoadError)
```

I googled the error and it seemed to be related to Rack 3 (?) but even manually adding `rackup` didn't help. The `require 'rack/handler'` seems to have been added here? https://github.com/evilmartians/capybara-thruster/commit/c65399c7e49396d7a49c7f031664eb4a99b26a53

## Environment

**Ruby Version:** 3.3.5

**Rack:** 3.0.11

**Capybara Thruster Version:** 0.1.1

**Comment by julianrubisch** [comment]
Can confirm that downgrading to 0.1.0 seems to fix the issue

**Comment by palkan** [comment]
Don't know why we added `require 'rack/handler'`. Dropped in 0.1.2. Could you check please?

**Comment by julianrubisch** [comment]
Yep, that fixed it, thanks!
